name: portfolio
description: Portfolio.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=2.16.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^1.0.3
  intl: ^0.17.0
  flutter_localizations:
    sdk: flutter
  auto_route: ^3.2.2
  hooks_riverpod: ^1.0.3
  flutter_hooks: ^0.18.2
  json_serializable: ^6.1.4
  freezed_annotation: ^1.1.0
  google_fonts: ^2.3.1
  sizer: ^2.0.15
  enum_to_string: ^2.0.1
  fluttertoast: ^8.0.8
  device_preview: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner: ^2.1.7
  flutter_gen_runner: ^4.1.5
  auto_route_generator: ^3.2.1
  freezed: ^1.1.1
  fimber: ^0.6.5

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/img/
    - assets/svg/

flutter_gen:
  integrations:
    flutter_svg: true